Feat java21 runtime (#22)
aws/aws-sam-build-images pull request #110
Opened 2023-11-14 05:10 UTC by hawflau

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-11-15 22:26 UTC, mndeveci requested changes

2023-11-15 22:26 UTC, mndeveci commented on build-image-src/Dockerfile-java21
> +FROM public.ecr.aws/lambda/java:21-preview-$IMAGE_ARCH
Should we remove preview tag?

2023-11-15 23:30 UTC, hawflau commented on build-image-src/Dockerfile-java21
> +FROM public.ecr.aws/lambda/java:21-preview-$IMAGE_ARCH
```suggestion
FROM public.ecr.aws/lambda/java:21-$IMAGE_ARCH
```

2023-11-16 00:21 UTC, mndeveci approved these changes

2023-11-16 00:24 UTC, hnnasit approved these changes

2023-11-16 19:59 UTC, merged