Add python3.12 build image
aws/aws-sam-build-images pull request #114
Opened 2023-11-15 20:58 UTC by hawflau

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-11-15 22:14 UTC, mndeveci requested changes

2023-11-15 22:14 UTC, mndeveci commented on build-image-src/Dockerfile-python312
> +FROM public.ecr.aws/lambda/python:3.12-preview-$IMAGE_ARCH
image points to preview, I think we should replace this with GA image?

2023-11-15 23:33 UTC, hawflau commented on build-image-src/Dockerfile-python312
> +FROM public.ecr.aws/lambda/python:3.12-preview-$IMAGE_ARCH
```suggestion
FROM public.ecr.aws/lambda/python:3.12-$IMAGE_ARCH
```

2023-11-16 00:19 UTC, mndeveci approved these changes

2023-11-16 00:27 UTC, hnnasit approved these changes

2023-11-16 18:18 UTC, merged