chore: bump  go version to 1.21.6
aws/aws-sam-build-images pull request #126
Opened 2024-01-24 10:19 UTC by rehleinBo

*Description of changes:*
Update to go 1.21.6 and lib update of go test app.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-01-29 19:31 UTC, hawflau requested changes
Thanks for your contribution. I left a small comment

2024-01-29 19:31 UTC, hawflau commented on build-image-src/Dockerfile-go1x
> +RUN curl -L https://go.dev/dl/go1.21.6.linux-amd64.tar.gz | tar -zx -C /usr/local
nit: we could fetch latest Go version too

```suggestion
RUN curl -L https://go.dev/dl/$(curl -L "https://go.dev/VERSION/?m=text" | grep go1.).linux-amd64.tar.gz | tar -zx -C /usr/local
```

2024-01-31 06:01 UTC, rehleinBo commented
> Thanks for your contribution. I left a small comment

Thank you for the suggestions.

2024-02-02 00:55 UTC, mndeveci approved these changes

2024-02-05 17:48 UTC, hawflau approved these changes

2024-02-05 17:49 UTC, merged